
SRC_C += $(DIR)/core/rtw_xmit.o	\
	$(DIR)/core/rtw_recv.o \
	$(DIR)/osdep/freertos/lxbus_intf.o \
	$(DIR)/osdep/freertos/freertos_skbuff.o \
	$(DIR)/osdep/freertos/freertos_isr.o \
	$(DIR)/osdep/freertos/freertos_recv.o \
	$(DIR)/osdep/freertos/freertos_xmit.o \
	$(DIR)/osdep/freertos/rtk_wlan_if.o \
	$(DIR)/osdep/lwip_intf.o \

SRC_C += $(DIR)/hal/phydm/phydm_cfotracking.o \
	$(DIR)/hal/phydm/phydm_antdiv.o \
	$(DIR)/hal/phydm/phydm_math_lib.o \
	$(DIR)/hal/phydm/phydm_phystatus.o \
	$(DIR)/hal/phydm/phydm_soml.o
	
SRC_C += $(DIR)/hal/rtl8721d/src/lx_bus/rtl8721d_xmit.o
SRC_C += $(DIR)/hal/rtl8721d/src/rtl8721d_rf_onoff.o

